name: CompassEx
main: de.philworld.bukkit.compassex.CompassEx
version: $MAVEN-VERSION-NUMBER$
softdepend: [dynmap]
commands:
   compassex:
      description: Main CompassEx command.
      aliases: [cp, compass]
