name: CompassEx
main: de.philworld.bukkit.compassex.CompassEx
version: $MAVEN-VERSION-NUMBER$
softdepend: [dynmap]
commands:
   compass:
      description: Points your compass towards something.
      aliases: [cp, compassex]
      usage: |
        Wrong usage of /<command>
        * /<command> reset - Resets the compass to spawn.
        * /<command> player [player] - Points the compass to given players position.
        * /<command> pos [x] [y] [z] - Points to the given position.
        * /<command> live [player] - Tracks the given player live.
        * /<command> hide - Protect yourself against tracking.
        * /<command> hidden - Are you hidden right now?
        
permissions:
    'compassex.*':
        description: Gives access to all the CompassEx commands.
        default: op
        children:
          compassex.reset: true
          compassex.here: true
          compassex.live: true
          compassex.direction: true
          compassex.height: true
          compassex.bed: true
          compassex.hide: true
          compassex.deathpoint: true
          compassex.pos: true
          compassex.player: true
          compassex.admin: true
          compassex.help: true
          compassex.save: true
          compassex.load: true
          compassex.remove.public.any: true
          compassex.remove.private.any: true
          compassex.list.any: true
          compassex.info.any: true
          compassex.privatize.any: true
          compassex.publicize.any: true
    compassex.help:
      description: Acces to the help page.
      default: op
    compassex.reset:
      description: Resets the compass to spawn.
      default: op
    compassex.here:
        description: Sets the compass to the players current position.
        default: op
    compassex.bed:
        description: Sets the compass to your bed.
        default: op
    compassex.direction: 
        description: Sets the compass to a direction.
        default: op
    compassex.live:
        description: Tracks the given player live.
        default: op
    compassex.height:
        description: Gets the height difference between you and your compass target.
        default: op
    compassex.hide:
        description: Protect from being tracked from others.
        default: op
    compassex.deathpoint:
        description: Allows to set the compass to the latest death point.
        default: op
    compassex.pos:
        description: Sets the compass to the given position.
        default: op
    compassex.player:
        description: Tracks the given player.
        default: op
    compassex.admin:
        description: Allows the user to even track hidden users.
        default: op
    
    
    compassex.save:
        description: Allows you to save your current position or compass target
        default: op
    compassex.load:
        description: Allows you to set your compass to public and owned private locations
        default: op
    
    
    compassex.remove.public:
        description: Allows you to remove owned public compass targets
        default: op
    compassex.remove.public.any:
        children:
            compassex.remove.public: true
        description: Allows you to remove any public compass target, owned and unowned
        default: op
    compassex.remove.private:
        description: Allows you to remove owned private compass targets
        default: op
    compassex.remove.private.any:
        children:
            compassex.remove.private: true
        description: Allows you to remove any private compass target, owned and unowned
        default: op
    compassex.remove:
        children:
            compassex.remove.private: true
        description: Alias for compassex.remove.private. Never used in code.
        default: op
    
    
    compassex.list:
        description: Allows you to list all public and all owned private compass targets
        default: op
    compassex.list.any:
        children:
            compassex.list: true
        description: Allows you to list all public and all private compass targets, owned and unowned.
        default: op
    
    
    compassex.info:
        description: Allows you to see your current, or public and owned private compass target's coordinates
        default: op
    compassex.info.any:
        children:
            compassex.info: true
        description: Allows you to see your current, or public and any private compass target's coordinates
        default: op
    
    
    compassex.privatize:
        description: Allows you to convert owed public compass targets to private compass targets
        default: op
    compassex.privatize.any:
        children:
            compassex.privatize: true
        description: Allows you to convert any public compass target to private compass target
        default: op
    
    
    compassex.publicize:
        description: Allows you to convert owned private compass targets to public compass targets
        default: op
    compassex.publicize.any:
        children:
            compassex.publicize: true
        description: Allows you to convert private compass targets to public compass targets