name: CompassEx
main: de.philworld.bukkit.compassex.CompassEx
version: $MAVEN-VERSION-NUMBER$
softdepend: [dynmap]
commands:
   compass:
      description: Points your compass towards something.
      aliases: [cp, compassex]
